plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.dasihaebom'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {

	// Spring Web
	implementation 'org.springframework.boot:spring-boot-starter-web'

	//JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Springdoc OpenAPI (Swagger)
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'

	// MySQL
	runtimeOnly 'com.mysql:mysql-connector-j'

	// WebFlux
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-impl:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'

	// SECURITY
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// REDIS
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// QueryDLS
	implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
	annotationProcessor "com.querydsl:querydsl-apt:5.0.0:jakarta"
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"

	// Thymeleaf - HTML 템플릿에 데이터를 채워넣기 위한 라이브러리
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	// openhtmltopdf - HTML을 PDF로 변환하기 위한 라이브러리
	implementation 'com.openhtmltopdf:openhtmltopdf-pdfbox:1.0.10'

	//Jackson 라이브러리가 Java 8의 날짜/시간(LocalDate, LocalDateTime 등)을 처리하도록 돕는 모듈
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}

tasks.named('test') {
	useJUnitPlatform()
}
